## Практическое задание 4-2

In [1]:
import numpy as np
import scipy.linalg

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__Решение__

a) $detA=\begin{vmatrix}
1 & -2\\3 & -4\end{vmatrix}=1\cdot(-4)-3\cdot(-2)=2\neq 0$

$detA_1=\begin{vmatrix}
1 & -2\\7 & -4\end{vmatrix}=1\cdot(-4)-7\cdot(-2)=10$

$detA_2=\begin{vmatrix}
1 & 1\\3 & 7\end{vmatrix}=1\cdot7-3\cdot1=4$

$x_1=\frac{detA_1}{detA}=\frac{10}{2}=5$

$x_2=\frac{detA_2}{detA}=\frac{4}{2}=2$

б) $detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}1 & -3\\ 4 & 1 \end{vmatrix}-
\begin{vmatrix}-1 & 5\\ 4 & 1 \end{vmatrix}+
2\begin{vmatrix}-1 & 5 \\ 1 & -3\end{vmatrix}=
2(1+12)-(-1-20)+2(3-5)=43\neq 0,$

$detA_1=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
\begin{vmatrix}-1 & 5\\ 1 & -3 \end{vmatrix}-
4\begin{vmatrix}10 & 5\\ -2 & -3 \end{vmatrix}+
\begin{vmatrix}10 & -1 \\ -2 & 1\end{vmatrix}=
(3-5)-4(-30+10)+(10-2)=86$

$detA_2=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
2\begin{vmatrix}-2 & -3\\ 1 & 1 \end{vmatrix}-
\begin{vmatrix}10 & 5\\ 1 & 1 \end{vmatrix}+
2\begin{vmatrix}10 & 5 \\ -2 & -3\end{vmatrix}=
2(-2+3)-(10-5)+2(-30+10)=-43$

$detA_2=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}1 & -2\\ 4 & 1 \end{vmatrix}-
\begin{vmatrix}-1 & 10\\ 4 & 1 \end{vmatrix}+
2\begin{vmatrix}-1 & 10 \\ 1 & -2\end{vmatrix}=
2(1+8)-(-1-40)+2(2-10)=43$

$x_1=\frac{detA_1}{detA}=\frac{86}{43}=2$

$x_2=\frac{detA_2}{detA}=\frac{-43}{43}=-1$

$x_3=\frac{detA_3}{detA}=\frac{43}{43}=1$

In [2]:
A = np.array([[1, -2], [3, -4]])
b_A = np.array([[1, 7]])

B = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b_B = np.array([[10, -2, 1]])

X_A = np.array([np.linalg.det(np.hstack((b_A.T, A[:, 1:])))/np.linalg.det(A),
                 np.linalg.det(np.hstack((A[:, :-1], b_A.T)))/np.linalg.det(A)])

X_B = np.array([np.linalg.det(np.hstack((b_B.T, B[:, 1:])))/np.linalg.det(B),
                 np.linalg.det(np.hstack((B[:, 0:1], b_B.T, B[:, -1:])))/np.linalg.det(B),
                 np.linalg.det(np.hstack((B[:, :-1], b_B.T)))/np.linalg.det(B)])

print(f"Корни системы уравнений 'а)':\n{X_A}")
print(f"Корни системы уравнений 'б)':\n{X_B}")

Корни системы уравнений 'а)':
[5. 2.]
Корни системы уравнений 'б)':
[ 2. -1.  1.]


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__Решение__

__a)__ Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$.

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix},\quad$
а матрица $L$ —
$\quad\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}.$

Далее умножим вторую строку на $4$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

В итоге получим: $\quad$
$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},\quad
L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$$$$

__б)__ Вычтем первую строку из остальных, умноженную на $2, 3, 4$ соответственно. Запишем коэффициенты на позиции $l_{21}, l_{31}, l_{41}$.

Промежуточные матрицы: $\quad U$ —
$\quad\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix},\quad$
$L$ —
$\quad\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix}.$

Далее умножим вторую строку на $5$ и вычтем ее из третьей и умножим вторую строку на $6$ и вычтем ее из четвертой. Запишем полученные коэффициенты $5, 6$ на соответствующие позиции $l_{32}, l_{42}$

Промежуточные матрицы: $\quad U$ —
$\quad\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix},\quad$
$L$ —
$\quad\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & l_{43} & 1
\end{pmatrix}.$

Далее умножим третью строку на $7$ и вычтем ее из четвертой. При этом в матрицу $L$ на место $l_{43}$ запишем $7$

В итоге получим: $\quad$
$U$ —
$\quad\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix},\quad$
$L$ —
$\quad\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}.$

In [3]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
B = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 2, 18], [4, 22, 53, 33]])

PL_A, U_A = scipy.linalg.lu(A, permute_l=True)
PL_B, U_B = scipy.linalg.lu(B, permute_l=True)

print(f"LU-разложение для матрицы A:\nL-матрица:\n{PL_A}\nU-матрица:\n{U_A}\nLU произведение:\n{np.dot(PL_A, U_A)}")
print('\n')
print(f"LU-разложение для матрицы B:\nL-матрица:\n{PL_B}\nU-матрица:\n{U_B}\nLU произведение:\n{np.dot(PL_B, U_B)}")

LU-разложение для матрицы A:
L-матрица:
[[0.33333333 0.8        1.        ]
 [0.66666667 1.         0.        ]
 [1.         0.         0.        ]]
U-матрица:
[[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]
LU произведение:
[[ 1.  2.  4.]
 [ 2.  9. 12.]
 [ 3. 26. 30.]]


LU-разложение для матрицы B:
L-матрица:
[[ 0.25       0.75      -0.0619469  1.       ]
 [ 0.5        1.         0.         0.       ]
 [ 0.75      -0.25       1.         0.       ]
 [ 1.         0.         0.         0.       ]]
U-матрица:
[[  4.          22.          53.          33.        ]
 [  0.          -6.         -18.5         -7.5       ]
 [  0.           0.         -42.375       -8.625     ]
 [  0.           0.           0.           0.84070796]]
LU произведение:
[[ 1.  1.  2.  4.]
 [ 2.  5.  8.  9.]
 [ 3. 18.  2. 18.]
 [ 4. 22. 53. 33.]]


__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [4]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
B = np.array([1, -6, -5])

PL, U = scipy.linalg.lu(A, permute_l=True)

print(f"Корни СЛАУ, найденные с помощью LU-разложения:\n{np.around(np.dot(np.linalg.inv(U), np.dot(np.linalg.inv(PL), B)))}")
print(f"Корни СЛАУ, найденные с помощью обратной матрицы:\n{np.around((np.dot(np.linalg.inv(A), B)))}")
print(f"Корни СЛАУ, найденные с помощью функции solve:\n{np.around((np.linalg.solve(A, B)))}")

Корни СЛАУ, найденные с помощью LU-разложения:
[-1.  0.  1.]
Корни СЛАУ, найденные с помощью обратной матрицы:
[-1.  0.  1.]
Корни СЛАУ, найденные с помощью функции solve:
[-1.  0.  1.]


__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__Решение__

Произведем разложение на $LL^{T}$:

$l_{11}=\sqrt{a_{11}}=9,$

$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{\sqrt{9}}=-5,$

$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{\sqrt{9}}=5,$

$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 5^2}=5,$

$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\cdot(-15-(-5)\cdot 5)=\frac{1}{5}\cdot 10=2,$

$l_{33}=\sqrt{a_{33}-l_{13}^{2}-l_{23}^{2}}=\sqrt{38-25-4}=3.$

Получили матрицу 

$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$

Решим систему $Ly=b:$

$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$

$y_{1} = 59,$

$y_{2}=\frac{-460+295}{5}=-33,$

$y_{3}=\frac{193-295+66}{3}=-12.$

И решим систему $L^{T}x=y:$

$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$

$x_{3}=\frac{-12}{3}=-4,$

$x_{2}=\frac{-33+8}{5}=-5,$

$x_{1}=\frac{59-25+20}{9}=6.$

In [5]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
B = np.array([531, -460, 193])

L = np.linalg.cholesky(A)
Y = np.dot(np.linalg.inv(L), B)
X = np.dot(np.linalg.inv(L.T), Y)

print(f'Матрица L из разложения Холецкого:\n{L}\n')
print(f'Y из разложения Холецкого:\n{Y}\n')
print(f'X из разложения Холецкого:\n{X}')

Матрица L из разложения Холецкого:
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]

Y из разложения Холецкого:
[ 59. -33. -12.]

X из разложения Холецкого:
[ 6. -5. -4.]


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [6]:
def kramer_metod(A, B):
    
    det_A = np.linalg.det(A)
    
    if det_A!=0 and A.shape[0]==A.shape[1]:
        
        M = np.array([])
        X = []
        
        for j in range(len(A)):
            
            M = A.copy()
            M[:, j] = B
            X.append(round(np.linalg.det(M)/det_A))
            
        return X
    else:
        return False

In [7]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
B = np.array([[531, -460, 193]])

print(kramer_metod(A, B))

[6.0, -5.0, -4.0]
