## Практическое задание к уроку 2-1

In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) $AB$ и $BA$ матрицы не определены

б) $AB$ матрица $2\times 3$; $BA$ матрица не определена

в) $AB$ матрица $8\times 8$; $BA$ матрица $3\times 3$

г) $AB$ и $BA$ матрицы $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
%%latex
\begin{eqnarray*}A+B=\left(\begin{array}{cc}5&-3\\3&5\end{array}\right)\end{eqnarray*}
\begin{eqnarray*}\end{eqnarray*}
\begin{eqnarray*}A*B=\left(\begin{array}{cc}(1*4+(-2)*0)&(1*(-1)+(-2)*5)\\(3*4+0*0)&(3*(-1)+0*5)\end{array}\right)=
\left(\begin{array}{cc}4&-11\\12&-3\end{array}\right)\end{eqnarray*}
\begin{eqnarray*}\end{eqnarray*}
\begin{eqnarray*}B*A=\left(\begin{array}{cc}(4*1+(-1)*3)&(4*(-2)+(-1)*0)\\(0*1+5*3)&(0*(-2)+5*0)\end{array}\right)=
\left(\begin{array}{cc}1&-8\\15&0\end{array}\right)\end{eqnarray*}

<IPython.core.display.Latex object>

In [3]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A + B =\n{(A + B)}')
print(f'A * B =\n{np.dot(A, B)}')
print(f'B * A =\n{np.dot(B, A)}')

A + B =
[[ 5 -3]
 [ 3  5]]
A * B =
[[  4 -11]
 [ 12  -3]]
B * A =
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [4]:
%%latex
\begin{eqnarray*}3A-2B+4C=3*\left(\begin{array}{cc}1&7\\3&-6\end{array}\right)-2*
\left(\begin{array}{cc}0&5\\2&-1\end{array}\right)+4*\left(\begin{array}{cc}2&-4\\1&1\end{array}\right)=
\left(\begin{array}{cc}11&-5\\9&-12\end{array}\right)\end{eqnarray*}

<IPython.core.display.Latex object>

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'3A - 2B + 4C =\n{3*A-2*B+4*C}')

3A - 2B + 4C =
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [6]:
%%latex
\begin{eqnarray*}A^T=\left(\begin{array}{ccc}4&5&2\\1&-2&3\end{array}\right)\end{eqnarray*}\begin{eqnarray*}\end{eqnarray*}
\begin{eqnarray*}AA^T=\left(\begin{array}{ccc}
                            (4*4+1*1)&(4*5+(-2)*1)&(4*2+1*3)\\
                            (5*4+(-2)*1)&(5*5+(-2)*(-2))&(5*2+(-2)*3)\\
                            (2*4+3*1)&(2*5+(-2)*3)&(2*2+3*3)\end{array}\right)=
\left(\begin{array}{ccc}17&18&11\\18&29&4\\11&4&10\end{array}\right)\end{eqnarray*}\begin{eqnarray*}\end{eqnarray*}
\begin{eqnarray*}A^TA=\left(\begin{array}{cc}
                            (4*4+5*5+2*2)&(4*1+5*(-2)+2*3)\\
                            (4*1+5*(-2)+2*3)&(1*1+(-2)*(-2)+3*3)\end{array}\right)=
\left(\begin{array}{ccc}45&0\\0&14\end{array}\right)\end{eqnarray*}

<IPython.core.display.Latex object>

In [7]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'A*A^T = \n{np.dot(A, A.T)}')
print(f'\nA^T*A = \n{np.dot(A.T, A)}')

A*A^T = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A^T*A = 
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [8]:
def matrix_multiplication(M_1, M_2):
    
    def size_matrix(M):
        
        i = len(M)
        j = set()
        
        for line in M:
            
            j.add(len(line))

        if len(j) > 1:
            return False, False
        else:
            return i, j.pop()
        
    M_1_size, M_2_size = size_matrix(M_1), size_matrix(M_2)
    
    if M_1_size[1]==M_2_size[0] and M_1_size[1]!=False:
        
        M_2_transposed = list(map(list, zip(*M_2)))
        M_mult = [[None for elm in range(M_2_size[1])] for line in range(M_1_size[0])]
        
        for i, line_M_1 in enumerate(M_1):
            
            for j, line_M_2 in enumerate(M_2_transposed):
                
                M_mult[i][j] = sum(list(map(lambda x, y: x*y, line_M_1, line_M_2)))
                
        return M_mult
    else:
        return M_1_size, M_2_size, f'Произведение матриц (векторов) не определено'

In [9]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
B = [[1, 2], [3, 4], [5, 6]]

print(f'A*B = {matrix_multiplication(A, B)}')

a = [[1, 3, 4, 5]]
b = [[1], [2], [3], [4]]

print(f'A*B = {matrix_multiplication(a, b)}')
print(f'B*A = {matrix_multiplication(b, a)}')

A*B = [[22, 28], [49, 64], [76, 100], [103, 136]]
A*B = [[39]]
B*A = [[1, 3, 4, 5], [2, 6, 8, 10], [3, 9, 12, 15], [4, 12, 16, 20]]
