## Дополнительное практическое задание к уроку 5

In [1]:
import numpy as np
from sklearn import datasets
from pandas import DataFrame

In [2]:
iris = datasets.load_iris()
iris_frame = DataFrame(datasets.load_iris().data)
iris_frame.columns = iris.feature_names
iris_frame['target'] = iris.target
iris_frame['name'] = iris_frame.target.apply(lambda x : iris.target_names[x])
iris_frame.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target    name  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa  
5       0  setosa  
6       0  setosa  
7       0  setosa  
8       0  setosa  
9       0  setosa

Определим матрицу признаков

In [3]:
A = np.array(iris_frame[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']])
print(f'Ранг матрицы признаков: {np.linalg.matrix_rank(A)}')

Ранг матрицы признаков: 4


In [4]:
U, s, V = np.linalg.svd(A)
print(f'Признаки:\n{s}')
print(f'Вес признаков:\n{[itm/sum(s) for itm in s]}')

Признаки:
[95.95991387 17.76103366  3.46093093  1.88482631]
Вес признаков:
[0.8059340691495326, 0.14916876798004958, 0.029067159767294914, 0.015830003103122967]


Можем избавиться от 2 признаков, т.к. их вес в сумме менее 5%

In [5]:
s[-2:] = 0
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
A_new = np.dot(np.dot(U, D), V)
print(f'Ранг новой матрицы признаков: {np.linalg.matrix_rank(A_new)}')

Ранг новой матрицы признаков: 2


Найдем ковариационную матрицу, и сделаем сингулярное разложение

In [6]:
A_cov = np.cov(A_new, rowvar=False)
U_cov, s_cov, V_cov = np.linalg.svd(A_cov)
print(f'Ковариационная матрица:\n{A_cov}')

Ковариационная матрица:
[[ 0.68222377 -0.0208085   1.28603382  0.52241054]
 [-0.0208085   0.13721124 -0.34521301 -0.15395272]
 [ 1.28603382 -0.34521301  3.10979132  1.2939947 ]
 [ 0.52241054 -0.15395272  1.2939947   0.53951014]]


In [7]:
print(f'Получили матрицу перехода:\n{V_cov}')

Получили матрицу перехода:
[[-0.36356257  0.08751286 -0.85655868 -0.35562761]
 [-0.71605943 -0.66010344  0.17801903  0.1408246 ]
 [ 0.07877261 -0.19314343  0.32918864 -0.9209372 ]
 [-0.59065729  0.72062512  0.35531859 -0.07464655]]


In [8]:
print(np.dot(A_new, V_cov))

[[-4.37162073 -1.99385986 -3.20713842 -2.62443402]
 [-4.05130344 -1.79076734 -2.92341748 -2.60276413]
 [-4.01839078 -1.82540772 -2.94171863 -2.43437125]
 [-3.93387802 -1.72323382 -2.8253224  -2.57410972]
 [-4.35833905 -1.99953512 -3.20742501 -2.58133753]
 [-4.72065564 -2.09617774 -3.41457861 -3.00422674]
 [-4.05161727 -1.82581294 -2.95348557 -2.49847039]
 [-4.28075866 -1.91497582 -3.10847016 -2.6819726 ]
 [-3.73310597 -1.63533531 -2.68116976 -2.44258718]
 [-4.10142358 -1.8107271  -2.9577081  -2.64153312]
 [-4.6276393  -2.10671782 -3.39161791 -2.78983547]
 [-4.17661492 -1.84176704 -3.01008849 -2.69641468]
 [-3.9978629  -1.77842278 -2.89449576 -2.5346719 ]
 [-3.70258236 -1.72349505 -2.74604538 -2.11867767]
 [-4.95547201 -2.3683294  -3.72794956 -2.65109865]
 [-5.08352083 -2.37080944 -3.77408233 -2.89537574]
 [-4.6952584  -2.18933718 -3.48549046 -2.67542714]
 [-4.36981474 -1.98124496 -3.19573329 -2.65864734]
 [-4.84623635 -2.1530363  -3.50635086 -3.08086773]
 [-4.50205859 -2.04985926 -3.29