## Дополнительное практическое задание к уроку 5

In [1]:
import numpy as np
from sklearn import datasets
from pandas import DataFrame

In [2]:
iris = datasets.load_iris()
iris_frame = DataFrame(datasets.load_iris().data)
iris_frame.columns = iris.feature_names
iris_frame['target'] = iris.target
iris_frame['name'] = iris_frame.target.apply(lambda x : iris.target_names[x])
iris_frame.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target    name  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa  
5       0  setosa  
6       0  setosa  
7       0  setosa  
8       0  setosa  
9       0  setosa

Определим матрицу признаков

In [3]:
A = np.array(iris_frame[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']])
print(f'Ранг матрицы признаков: {np.linalg.matrix_rank(A)}')

Ранг матрицы признаков: 4


In [4]:
U, s, V = np.linalg.svd(A)
print(f'Признаки:\n{s}')
print(f'Вес признаков:\n{[itm/sum(s) for itm in s]}')

Признаки:
[95.95991387 17.76103366  3.46093093  1.88482631]
Вес признаков:
[0.8059340691495326, 0.14916876798004958, 0.029067159767294914, 0.015830003103122967]


Можем избавиться от 2 признаков, т.к. их вес в сумме менее 5%

In [5]:
s[-2:] = 0
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
A_new = np.dot(np.dot(U, D), V)
print(f'Ранг новой матрицы признаков: {np.linalg.matrix_rank(A_new)}')

Ранг новой матрицы признаков: 2


Найдем ковариационную матрицу, и сделаем сингулярное разложение

In [6]:
A_cov = np.cov(A_new, rowvar=False)
U_cov, s_cov, V_cov = np.linalg.svd(A_cov)
print(f'Ковариационная матрица:\n{A_cov}')

Ковариационная матрица:
[[ 0.68222377 -0.0208085   1.28603382  0.52241054]
 [-0.0208085   0.13721124 -0.34521301 -0.15395272]
 [ 1.28603382 -0.34521301  3.10979132  1.2939947 ]
 [ 0.52241054 -0.15395272  1.2939947   0.53951014]]


In [7]:
print(f'Получили матрицу перехода:\n{V_cov}')

Получили матрицу перехода:
[[-0.36356257  0.08751286 -0.85655868 -0.35562761]
 [-0.71605943 -0.66010344  0.17801903  0.1408246 ]
 [ 0.07877261 -0.19314343  0.32918864 -0.9209372 ]
 [-0.59065729  0.72062512  0.35531859 -0.07464655]]


Перейдем к новому базису с помощью матрицы перехода

In [8]:
print(np.round(np.dot(V_cov, A_new.T).T, 10))

[[-2.81818175 -5.68487355 -0.         -0.        ]
 [-2.78922566 -5.21160995 -0.         -0.        ]
 [-2.61335471 -5.21822065 -0.         -0.        ]
 [-2.75706148 -5.04500056 -0.         -0.        ]
 [-2.7730742  -5.67927795 -0.         -0.        ]
 [-3.2203385  -6.08216213 -0.         -0.        ]
 [-2.68071451 -5.24675103 -0.         -0.        ]
 [-2.87623264 -5.52945536 -0.         -0.        ]
 [-2.61619567 -4.78756989 -0.         -0.        ]
 [-2.83056748 -5.27390085 -0.         -0.        ]
 [-2.99540381 -6.01391017 -0.         -0.        ]
 [-2.889176   -5.36844157 -0.         -0.        ]
 [-2.71730665 -5.15408647 -0.         -0.        ]
 [-2.27855776 -4.84946246 -0.         -0.        ]
 [-2.85760738 -6.55177068 -0.         -0.        ]
 [-3.1143391  -6.66263548 -0.         -0.        ]
 [-2.87771503 -6.15336974 -0.         -0.        ]
 [-2.85374451 -5.67079109 -0.         -0.        ]
 [-3.30259579 -6.24505207 -0.         -0.        ]
 [-2.91314652 -5.85102022 -0.  